### ISSUE TITLE
Cannot use map(to: ) in Combine

### ISSUE THREAD

**Issue by ghost** [jdisho/TinyNetworking#21]
When I use TinyNetworking with combine like the example. I cannot use the map(to:) to map the object.
![Screen Shot 2019-11-06 at 10 43 03 AM](https://user-images.githubusercontent.com/47016587/68266870-fd154700-0082-11ea-87a5-7bba0df9eeef.png)

**Comment by jdisho** [comment]
Mind creating a PR with a fix? 😊

**Comment by jdisho** [comment]
I think this issue is not relevant anymore. In case I am wrong, please reopen this issue.

**Comment by asteiman** [comment]
Any update on this?

**Comment by jdisho** [comment]
I will release an update soon.

But for now, if it helps, you can try this. Should be fine 😊 

```swift 
tinyNetworking
    .requestPublisher(resource: .photo(id: id))
    .compactMap { $0.data }
    .decode(type: Codable.Type, decoder: JSONDecoder())
    .eraseToAnyPublisher()
```

**Comment by jdisho** [comment]
Fixed. Released in `v.4.0.1`. 🚀
