### ISSUE TITLE
Choose destination for Parameter Encoding

### ISSUE THREAD

**Issue by jdisho** [jdisho/TinyNetworking#6]
The latest release does not support the destination for parameters. 
`URLEncoding` creates an encoded query, which should be appended to any existing `URL` query or set as the `HTTP` body of the `URL` request. In the `2.0.0` release, only `requestWithEncodable` tasks are set in the `HTTP` body.

**Comment by jdisho** [comment]
```swift 
 var task: Task {
    var params: [String: Any] = ["foo": "bar"]
    let urlEncoding = URLEncoding(destination = .urlQuery)
    return .requestWithParameters(params, encoding: urlEncoding)
  }
// URL Query: https://abc.xyz/bla?foo=bar
```


```swift 
 var task: Task {
    var params: [String: Any] = ["foo": "bar"]
    let urlEncoding = URLEncoding(destination = .httpBody)
    return .requestWithParameters(params, encoding: urlEncoding)
  }
// HTTP body: foo=bar
```

**Comment by asteiman** [comment]
Do you think this is necessary? why not based on the request method?

Use the query for GET, use http body for POST, PUT and DELETE.

**Comment by jdisho** [comment]
Hey @asteiman! 
It can happen that some `GET` requests require parameters to be in the body and not encoded into the query.

**Comment by asteiman** [comment]
https://github.com/jdisho/TinyNetworking/pull/28
